/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RockPaperScissors } from "./RockPaperScissors";
export * as factories from "./factories";
export { RockPaperScissors__factory } from "./factories/RockPaperScissors__factory";
